GET /api/customers
Host: localhost:8080
Accept: application/json

###
GET /api/customers/64d9a8d5992f07816497834e
Host: localhost:8080
Accept: application/json

###
POST /api/customers
Host: localhost:8080
Accept: application/json
Content-Type: application/json

{
  "first_name": "Kishore",
  "last_name": "Kumar",
  "gender": "Male",
  "email": "kishorekumar@xmpl.com",
  "phone": "9876509876"
}
###
PATCH /api/customers/64d9a8d5992f07816497834e
Host: localhost:8080
Accept: application/json
Content-Type: application/json

{
    "city": "Vascodagama",
    "state": "Goa",
    "email": "kishore.kumar@example.com"
}
###
PATCH /api/customers/64d9a8d5992f07816497834e
Host: localhost:8080
Accept: application/json
Content-Type: application/json

{
    "email": "kishorekumar98765@gmail.com",
    "country": "India",
    "avatar": "https://robohash.org/reprehenderitnonoptio.png?size=50x50&set=set1"
}
###
